{{- if and .Values.secrets.kafkaSasl.enabled (not .Values.secrets.kafkaSasl.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "public-api.fullname" . }}
  labels:
    {{- include "public-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  KAFKA_SASL_USERNAME: {{ .Values.secrets.kafkaSasl.username | default "" | quote }}
  KAFKA_SASL_PASSWORD: {{ .Values.secrets.kafkaSasl.password | default "" | quote }}
{{- end }}